# Generated by Django 5.0.1 on 2024-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
