# Generated by Django 5.0.1 on 2024-02-02 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dream_team", "0003_formation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("goalkeeper", "Goalkeeper"),
                    ("defender", "Defender"),
                    ("midfielder", "Midfielder"),
                    ("forward", "Forward"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="team",
            name="users",
        ),
        migrations.AddField(
            model_name="team",
            name="users",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
